import("//build/package.gni")

static_library("blk_ufsinfo") {
  sources = [
    "set_info.c",
    "set_info.h",
    "ufsinfo.c",
    "ufsinfo.h",
  ]



deps = [
    "//third_party/ree-trusty/libnbl_vhm:acrn_headers",
    "//third_party/fdt",
    "//zircon/trusty/lib/lib/libc-trusty",
    "//third_party/hee-trusty/nbl_license_srv/lib:libnbl_nmt_tee",
  ]
}