import("//build/config/fuchsia/rules.gni")
import("//build/package.gni")

config("mt8668_eint_hw_headers") {
  include_dirs = [ "." ]
}

source_set("mt8668_eint_hw") {
  sources = [ "mt8668-eint-hw.c" ]
  public_configs = [ ":mt8668_eint_hw_headers" ]
}

driver_module("mt8668_board_drv") {
  output_name = "mt8668"

  sources = [
    "mt8668-board.c",
    "mt8668-wdt.c",
    "mt8668-ufs.c",
    "mt8668-alloc.c",
    "mt8668-spi.c",
    "mt8668-i2c.c",
    "mt8668-eint.c",
    "mt8668-rtc.c",
  ]

  defines = [ "_ALL_SOURCE=1" ]

  deps = [
    "//zircon/public/lib/ddk",
    "//zircon/public/lib/driver",
    "//zircon/public/lib/zx",
    "//garnet/drivers/soc/mt8668",
    ":mt8668_eint_hw",
  ]
}

package("mt8668") {
  system_image = true

  deps = [
    ":mt8668_board_drv",
  ]

   drivers = [
     {
       name = "mt8668.so"
     },
   ]
}
